export const NEW_MAIN_CATEGORY_REQUEST="NEW_MAIN_CATEGORY_LOGIN_REQUEST";
export const NEW_MAIN_CATEGORY_SUCCESS="NEW_MAIN_CATEGORY_LOGIN_SUCCESS";
export const NEW_MAIN_CATEGORY_FAIL="NEW_MAIN_CATEGORY_LOGIN_FAIL";

export const GET_ALL_CATEGORIES_REQUEST="GET_ALL_CATEGORIES_REQUEST"
export const GET_ALL_CATEGORIES_SUCCESS="GET_ALL_CATEGORIES_SUCCESS"
export const GET_ALL_CATEGORIES_FAIL="GET_ALL_CATEGORIES_FAIL"

export const NEW_SUBCATEGORY_REQUEST="NEW_SUBCATEGORY_REQUEST";
export const NEW_SUBCATEGORY_SUCCESS="NEW_SUBCATEGORY_SUCCESS";
export const NEW_SUBCATEGORY_FAIL="NEW_SUBCATEGORY_FAIL";